version: '3'
services:
  wechat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wechat
    volumes:
      - .:/workspace/
    environment:
      - TZ=Asia/Shanghai
      - CREDENTIAL_FILE=/run/secrets/credential
    command: "uvicorn --host 0.0.0.0 --port 3000 --reload main:app"
    secrets:
      - credential

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - wechat

secrets:
  credential:
    file: ./secret/credential.json
